import globals
import os
import subprocess

# Removes the quotation marks at the beginning and at the end of the variable
# It also removes the linux path /mnt/c/ 
# For more details, check the Environment variables section in the README file
# Besides, it converts all forward slashes to backlahses
VS_BUILD_PATH = os.environ["VS_BUILD_PATH"][8:-1].replace("/", "\\\\")

# Adds windows C drive to the path
VS_BUILD_PATH = "C:\\\\" + VS_BUILD_PATH

# This proccess builds a Visual Studio solution, previously generated by gensln command
# The specifications of this solution are defined in the Solution settings constants defined at the beginning of the file
subprocess.call(["cmd.exe", "/c", VS_BUILD_PATH, "{}.sln".format(globals.ENGINE_NAME), "/property:Configuration={}".format(globals.CONFIG)])